
package cat.marianao.daw2.m07.uf4.service.client.jaxws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TicketService", targetNamespace = "http://impl.service.uf4.m07.daw2.marianao.cat/", wsdlLocation = "http://localhost:8080/tickets/TicketService?wsdl")
public class TicketService
    extends Service
{

    private final static URL TICKETSERVICE_WSDL_LOCATION;
    private final static WebServiceException TICKETSERVICE_EXCEPTION;
    private final static QName TICKETSERVICE_QNAME = new QName("http://impl.service.uf4.m07.daw2.marianao.cat/", "TicketService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/tickets/TicketService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TICKETSERVICE_WSDL_LOCATION = url;
        TICKETSERVICE_EXCEPTION = e;
    }

    public TicketService() {
        super(__getWsdlLocation(), TICKETSERVICE_QNAME);
    }

    public TicketService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TICKETSERVICE_QNAME, features);
    }

    public TicketService(URL wsdlLocation) {
        super(wsdlLocation, TICKETSERVICE_QNAME);
    }

    public TicketService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TICKETSERVICE_QNAME, features);
    }

    public TicketService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TicketService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TicketServiceEndpoint
     */
    @WebEndpoint(name = "TicketServiceEndpointImplPort")
    public TicketServiceEndpoint getTicketServiceEndpointImplPort() {
        return super.getPort(new QName("http://impl.service.uf4.m07.daw2.marianao.cat/", "TicketServiceEndpointImplPort"), TicketServiceEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TicketServiceEndpoint
     */
    @WebEndpoint(name = "TicketServiceEndpointImplPort")
    public TicketServiceEndpoint getTicketServiceEndpointImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.service.uf4.m07.daw2.marianao.cat/", "TicketServiceEndpointImplPort"), TicketServiceEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TICKETSERVICE_EXCEPTION!= null) {
            throw TICKETSERVICE_EXCEPTION;
        }
        return TICKETSERVICE_WSDL_LOCATION;
    }

}
